### ISSUE TITLE
getannotation issue

### ISSUE THREAD

**Issue by falon** [robmueller/mail-imaptalk#4]
Hello,
 let suppose this IMAP query:
```
a getannotation "" "/vendor/EXAMPLE/*example.com" ("value.priv" "value.shared")
* ANNOTATION "" "/vendor/EXAMPLE/uc.example.com" ("value.priv" "maildata40")
* ANNOTATION "" "/vendor/EXAMPLE/example.com" ("value.priv" NIL "value.shared" NIL)
* ANNOTATION "" "/vendor/EXAMPLE/uc.example.com" ("value.shared" NIL)
a OK Completed
```
For some reason, for the same metadata (`uc.example.com` above) the Cyrus IMAP Server returns two rows.

Well, if I query
```
use Data::Dumper;
$Data::Dumper::Terse = 1;
$read=$IMAP->getannotation( "", "/vendor/EXAMPLE/*example.com", "value.*" );
print Dumper($read);
```

then I see:
```
{
  '' => {
          '/vendor/EXAMPLE/example.com' => {
                                              'value.shared' => undef,
                                              'value.priv' => undef
                                            },
          '/vendor/EXAMPLE/uc.example.com' => {
                                                 'value.shared' => undef
                                               }
        }
}
```

I suppose that `getannotation` saves only the result returned in the last row, if multiple rows for the same metadata occurs.

If I modify the `getannotation` to return only value.priv, I will correctly see:
```
{
  '' => {
          '/vendor/EXAMPLE/example.com' => {
                                              'value.priv' => undef
                                            },
          '/vendor/EXAMPLE/uc.example.com' => {
                                                 'value.priv' => 'maildata40'
                                               }
        }
}
```

**Comment by robmueller** [comment]
FYI GETANNOTATION is the ancient 2005 ANNOTATEMORE draft (https://tools.ietf.org/html/draft-daboo-imap-annotatemore-07) which became the METADATA RFC in 2009 (https://tools.ietf.org/html/rfc5464).

The ANNOTATION parser might be a bit messed up using `->getannotation()` calls because annoyingly, they ended up re-using the term ANNOTATION for the GETANNOTATION RFC (https://tools.ietf.org/html/rfc5257) which allows attaching an annotation to each message rather than to each mailbox/the server.

You should probably change all your code to use `->getmetadata()` instead, you've made me realise I should remove getannotation in the next version.
